site_name: Centre for Imaging Research (CIR)

repo_url: https://github.com/natmegsweden/documentation
repo_name: Show on GitHub
edit_uri: blob/main/docs/
site_url: https://natmegsweden.github.io/documentation/

theme: 
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  features:
      - announce.dismiss
      - content.action.view
      - content.action.edit
      - navigation.instant
      - navigation.instant.preview
      - navigation.tabs
      # - navigation.sections # Makes top level sections expandable
markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.tab:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - Home: index.md
  - NatMEG:
    - About: about-NatMEG.md
    - Preparation:
      - Apply electrodes: natmeg/lab/Electrodes-standard-setup.md
      - Digitization: natmeg/lab/Digitization-hpi.md
    - SQUID Acquisition: 
      - About TRIUX: natmeg/lab/TRIUX-specs.md
      - Acquisition: natmeg/lab/Acquisition.md
      - Tuning channels: natmeg/lab/Tuning.md 
      - Check channels: natmeg/lab/Check-channels.md
      - EEG: natmeg/lab/EEG-specs.md
      - Bio channels: natmeg/lab/Biochannels-specs.md
      - Lab notebook: natmeg/lab/Lab-notebook.md

    - OPM Acquisition: natmeg/lab/OPM-Acquisition.md
    
    - Stimulus Equipment:
      - Audio: 
        - Audio mixer: natmeg/lab/Audio-mixer.md
        - Speakers: natmeg/lab/Speakers-specs.md
        - Sound tubes: natmeg/lab/Soundtubes-specs.md
        - Audio file: natmeg/lab/Audiofile-specs.md
        - Behringer interface: natmeg/lab/Behringer-specs.md
        - B&K sound level: natmeg/lab/B&K-sound-level-meter-specs.md
      - Visual:
        - Screen and Projector: natmeg/lab/Screen-and-projector.md
      - Other: 
        - Pleasant touch: natmeg/lab/Pleasant-touch-specs.md
        - Tactile stimulator: natmeg/lab/Tactile-specs.md
        - Electric nerve stimulation: natmeg/lab/ENS-specs.md
        - Mechanical pain: natmeg/lab/Mechanical-pain-specs.md
        - Olfactometer: natmeg/lab/Olfaction-specs.md
        - New test-page: natmeg/test_new.md
    - Response Equipment: 
      - Eye-tracker: natmeg/lab/Eye-tracker.md
    - Presentation:
      - Presentation: natmeg/lab/Presentation.md
      - Presentation tips: natmeg/lab/Presentation-script-tips.md
      - Presentation examples: 
        - Auditory oddball: natmeg/lab/Presentation-code-example-Auditory-oddball-paradigm.md
        - Resting state: natmeg/lab/Presentation‐code‐example‐Resting‐state‐paradigm.md
    - Triggers: natmeg/lab/Triggers-specs.md
    - Other:
      - File naming: natmeg/lab/File-naming.md
      - Beyond compare: natmeg/lab/Beyond-compare.md
      - Maxfilter: natmeg/lab/Maxfilter.md
      - MSR:  natmeg/lab/MSR-specs.md
      - Monitors: natmeg/lab/Monitors.md
      - Acoustic-panels-specs: natmeg/lab/Acoustic-panels-specs.md
  - Server:
    - Set-up connection: 
      - Connect to Archive: natmeg/server/Connect-to-Archive.md
      - Connect to Storate: natmeg/server/Connect-to-Storage.md
      - Connect to Compute: natmeg/server/Connect-to-Compute.md
      - Close VNC connection: natmeg/server/Close-VNC-connection.md
    - Install software:
      - Set-up MNE on Compute: natmeg/server/Set-up-MNE-Python-on-Compute.md
      - Set-up FieldTrip on Compute: natmeg/server/Set-up-FieldTrip-on-Compute.md
      - Set-up FreeSurfer on Compute: natmeg/server/Guide-for-setting-up-Freesurfer-on-Compute.md
    - Analysis:
      - General: natmeg/server/tutorial_00_tips_for_writing_scripts.md
    # - Troubleshooting:
